
cache: &global_cache
  key: $CI_COMMIT_REF_SLUG
  paths:
  # 缓存
    - node_modules

stages: # 分段
  - install
  # - eslint
#  - build
  - start

install:
  tags:
    - run
  stage: install
  script:
    - sudo -i & cd /home/gitlab-runner/builds/tYTjy6R-/0/root/server_python_flask/ & pipenv install --skip-lock
  allow_failure: true


#build-job:
#  tags:
#    - sss
#  stage: build
#  script:
##    - sudo pyinstaller -F hack/runScrapy.py
##    - sudo -S cp -r -p ./dist/* /var/myClient/pythonFlask
#    - sudo rm -rf /home/gitlab-runner/builds/tYTjy6R-/0/root/server_python_flask/build
#    - sudo rm -rf /home/gitlab-runner/builds/tYTjy6R-/0/root/server_python_flask/dist

deploy-job:
  tags:
    - run
  stage: start
  script:
#    - sudo systemctl stop python_flask.service
#    - sudo systemctl start python_flask.service
    - echo $CI_PROJECT_NAMESPACE
    - sudo nohup python3 $CI_PROJECT_NAMESPACE + hack/runScrapy.py SERVER > pythonlog.file 2>&1 &
#    - sudo rm -rf /home/gitlab-runner/builds/tYTjy6R-/0/root/server_python_flask/build
#    - sudo rm -rf /home/gitlab-runner/builds/tYTjy6R-/0/root/server_python_flask/dist
    # - rsync -r --delete ./dist root@xxx.xxx.xxx.xxx:/usr/share/nginx/html
